---
title: "Statistical_Report_ADAR"
author: "Alexander Staub"
date: "September 11, 2020"
output: 
  html_document:
    code_folding: "hide"
    includes:
      after_body: footer.html
bibliography: C:\\R work\\Advanced data analytics with R\\Statistical Report\\references\\reference_list.bib        
---

Need to have an area of package loading and dataframe loading

# Abstract
[@Cameron.1994; @Craig.2017]

# Introduction

Online communities are developing into an area of increasing relevance for both practice and academic research in fields of economics, management and information systems management, to name a few. The reason being that the proliferation of the internet has reached nearly every corner of the world (Source - Cia factbook?) and is touching and forming an increasing number of areas relevant to work and life in general. Social Media platforms have developed from means to connect to old and new friends, to sources of news, organizing online and offline gatherings and conducting commerce. Special interest groups, from programming to brand enthusiasts, have moved from communicating and exchanging knowledge via listserves and e-mails, to creating and sharing everything from software code (Source on open source) to designs for physical objects (source for 3d printing papers) via dedicated virtual spaces hosted online. As it is reasonable to assume that the trend of interacting and communicating with eachother virtually and unimpeded by physical borders or geographical distance won't be declining in the forseeable future, it is essential to understand the behavior of individuals as well as groups in this relatively new enviornment.

First off, there are a number of different uses and definitions of the term online community, as well as different names for similar concepts, depending on the discipline or research question of interest. The research herein is concerned with the behavior of members creating and sharing knowledge within online communities seen as a new form of organization (@Puranam.2014).  They are broadly defined as virtual space of communication among members facilitated by ICT technology (Source), have a shared goal, mission or interests that can be centered around a particular product or an entire subject area (Source), which have porous or open organizational boundaries allowing for self selection in and out() and whose primary goal is to foster the collaborative and cummulative creation and sharing of information and knoweldge (Source). Hence, the context of relevance is distinct from social media platforms like Twitter and Facebook, that are means of connecting and sharing information with a (relatively) closed group of friends and acquaintances, as well as from temporary forms of organizing like crowd sourcing contests. 

Research in the area of online communities as defined above, has provided insight into, among other things, the design (Source), evolution (Source), outputs (Stanko) and governance (Lerner and Tirole source) of these new forms of organising. Regarding the latter aspect, one of the key questions that arises is how to steer the behavior of members in online communities, as online communities thrive and decline with the engagement of their members (Source - Oh and Jeon, Ma and Agrawal? Lappas?). This challenge is especially pressient for online communities, as contribution behavior in online commmunities is highly right skewed, i.e. a very small number of highly active and intrinsically motivated members is responsible for the majority of contributions in online communities (Source). Hence, the question of how to incentivize increased activity by a larger portion of participant is a natural consequence (Lurking sources). As opposed to closed forms of organising, where effort can be induced by monetary compensation and hierarchy, online communities' characteristics, like their potential unlimited size and fluid membership of participants (Source), make monetary incentives and hierarchical control less of a viable option. A steering mechanism that is commonly found in many online communities are symbolic awards in the form of virtual badges, medals, ranks, points etc (Source). 

Studies in this area of inquiry have investigated the impact of symbolic awards in online communities in the past. Therein it was found that the prospect of receiving rewards lead to postivie effects in terms of contribution behavior in the short (Park?) and long term (Source?), as well as mixed findings when investigating different types of members within communities (Goes?) or when investigating the distribution of activity types (Anderson). In addition, the reception of symbolic awards was found to lead to a decrease in activity levels when these awards were awarded conditional on fulfilling predetermined criteria (Goes?, Anderson?), while leading to sustained increase in knoweldge contributions when receiving the award was unexpected (Gallus). .. #More insights necessary.
What remains largely unkown however is how the introduction of a symbolic rewards impacts the contribution behavior of members within online community. This is of theoretical interest, as it would help understand how members of an organization react when previously non-incentivized activities are explicitely, symbolically rewarded. This would provide novel and relevant insights compared to previous studies, which have mainly focused on contexts where rewards for certain behaviors were already established and may have influenced the make-up of the community via self selecting in or out of the community by members based on the governance mechanisms. Furthermore, it would provide insight into a key organising challenge within new forms of organising as proposed by Puranam et al (2015), by ... (From a pervious abstract).

The goal of this statistical report is to investigate the effect that the introduction of conditional symbolic awards has on the knowledge contributions that users produce in response to questions posed by other users. Knowledge sharing in the form of answers is a common form of communication in online communities, some of the notable context examples which were the subject of scientific inquiry in the past include Sourceforge (Source), Quora, StackOverflow (Source) or Yahoo Answers (Source). Answering questions of fellow members requires at least some degree of time and effort commited by the answerer, without incurring any immedate or measurable benefit, while the question poser is rewarded with a potential solution for a problem. Reasons for users providing this effort have been connected to intrinsical motivation like the joy of problem solving or learning (source), as well as extrinsic benefits like reputational gain (Source) or deferred career benefits (Source). While it has been shown that the prospect of receiving a reward, even when it is intangible and non-monetary, can increase the effort provided by members (Source), there is reason to assume that the availbility of such rewards may reduce the contributions on average. Extrinsic incentives have been shown to lead to a decrease of intrinsic motivation among prospective as well as actual recipients in a number of settings (Source). This is especially salient when the goals to achieve set out by such conditional awards are lower than the orinal effort level by certain individuals, leading to a "moral licensing" or "done enough" effect (Source). Furthermore, it has been found that while such conditional awards can temporarily lead to a surge in rewarded activity, the levels tend to drop off after they receive the reward. Investigating this question within online communities will be of paritcular interest, as outlined above, contributions to these communities tend to be driven by a small group of committed members, who studies found to be largely intrinsically motivated (Von krogh source etc). Thus, this leads to the following hypothesis:
- The introduction of symbolic awards rewarding the fulfilment of predetermined criteria (conditional symbolic awards) will lead to a decline of the average answers provided by existing members of a community
 
 
In order to answer the research question of relevance, a natural experiment is exploited, in which a set of symbolic awards in the form of virtual badges was introduced into an online community focused on sharing knowledge and solving problems in the field of electrical engineering, was introduced on the 13th of April 2015. A difference in difference design is adopted, employing panel data on the user week-leve across 6 months before and after the introduction. The StackExchange Electrical Engineering online community was identified as a sufficently similar control community, which did not witness any change in their reward system during the time of relevance. Procedures like coding of individual members by individuals external to the research team, focusing on registered users and propensity score matching are employed to strengthen the identification strategy. 

# Data collection

```{r warning=FALSE, message=FALSE}
#loading the packages necessary for the entire analysis
library(tidyverse)
library(gridExtra)
library(lubridate)
library(Hmisc)
if (!require(psych)) install.packages("psych"); library(psych)  
if (!require(janitor)) install.packages("janitor"); library(janitor)  #for tabyl function
if (!require(RColorBrewer)) install.packages("RColorBrewer"); library(RColorBrewer)  
if (!require(MASS)) install.packages("MASS"); library(MASS)  #for nb.glm (from glm models.R)
if (!require(car)) install.packages("car"); library(car)  #for additional lm and glm plots and functions (from glm models.R)
if (!require(effects)) install.packages("effects"); library(effects)  #for plotting effects (from glm models.R)
if (!require(AER)) install.packages("AER"); library(AER)  #overdispersion test (from glm models.R)
if (!require(stargazer)) install.packages("stargazer"); library(stargazer)  #tables
if (!require(plm)) install.packages("plm"); library(plm)  #balanced panels
if (!require(anytime)) install.packages("anytime"); library(anytime) 
if (!require(tidyr)) install.packages("tidyr"); library(tidyr) #to get the "pivot_wider" 
if (!require(MatchIt)) install.packages("MatchIt"); library(MatchIt) #package for matching
if (!require(optmatch)) install.packages("optmatch"); library(optmatch) #package for optimal matching
if (!require(broom)) install.packages("broom"); library(broom) #for understanding regression results
if (!require(fixest)) install.packages("fixest"); library(fixest) #for the point estimate and error bar plots for pretrends
if (!require(lfe)) install.packages("lfe"); library(lfe) #for linear models with multiway clustering and fixed effects
if (!require(alpaca)) install.packages("alpaca"); library(alpaca) #for non-linear models with multiway clustering and fixed effects
if (!require(boot)) install.packages("boot"); library(boot) #for bootstrapped standard errors
if (!require(clusterSEs)) install.packages("clusterSEs"); library(clusterSEs) #for bootstrapped standard errors

#loading the necessary dataframes
load("data/w_panel_did_qual_as_regUs_6m_b.Rda")
load("data/qual_pre_panel_clean_coded.Rda")
load("data/qual_pre_panel_ee_coded.Rda")
```

To conclude this research, digital trace data was collected on the treatment and control community in two different ways. While Stackoverflow generously provides data dumps of every sub community, of which the electrical engineering community is one, data on the treatment community had to be scraped. A research assistant was tasked with writing the scraping program in order to get access, which was audited by the research team. For both communities, data was gathered on the post level, and then aggregated to the user-week level in order to provide the necessary analyses for this study. 

The control community was identified as relevant for a difference in difference study due to a number of factors. First of all, descriptions of the two communities were inspected by the researchers, which allowed the team to conclude that the topical focus of the two matched. While it has to be mentioned, that the main difference between the two communities is that the treatment community is owned and operated by a commercial parent company, the researchers observed thta the parent company does not excert control over content and interactions in the community which was coroborated by annecdotal evidence from the community manager. Secondly, tags used in posts made in each community were compared to assess whether there are large topical differences in the main topics that are discussed, which could be disconfirmed. + Q&A nature of both communities.    

Need to show the missing values as a count table that enumerates the NAs and non-nas

# Descriptive analysis of the sample

### Descriptive statistics unmatched
use the stargazer table imploying html here to check

### graphical representations

### propensity score matching

mention that you tried a number of different models including different combinations of variables as well as matching methods, and decided to use the matched unaltered and matched on quantiles given the distribution of propensity scores and matching variables.

use the propensity distribution plot and the distribution of variables here

### descriptives statistics matched -> as above, choose matched unaltered

### Transition to analysis

demonstrate the high overdispersion and large amount of 0s, which points towards the necessity of zero inflated poisson or NB model



# Analysis

### hypotheses that will be tested

### Pretrend analysis

will have to use the coeffplot here and try to include both in one. 
error check will be necessary

### Performance analysis

here the equation has to be placed
- just the general model first. If I have time, I will try to write out the regression equation for the poisson models etc. 

Models calculated based on suitable pretrends

wil have to use stargazer and decide on what I can fit into one table

#### Preconditions
need to run an qq plot to determine normality

# Concluding remarks

# References

